sudo: required
services:
  - docker

before_install:
  - docker build -t mcleanmusa/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mcleanmusa/react-test npm run test -- --coverage

after_success:
  - docker build -t mcleanmusa/complex-client ./client
  - docker build -t mcleanmusa/complex-nginx ./nginx
  - docker build -t mcleanmusa/complex-server ./server
  - docker build -t mcleanmusa/complex-worker ./worker
    
# Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
  - docker push mcleanmusa/complex-client
  - docker push mcleanmusa/complex-nginx
  - docker push mcleanmusa/complex-server
  - docker push mcleanmusa/complex-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "mutli-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-995672583397"
  bucker_path: "complex"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
